"""
Document record model — AI-generated documents (cover letters, tailored resumes).

This collection stores all documents generated by the Application workflow
agents (ResumeTailor, CoverLetterWriter). Each document goes through a
human-in-the-loop approval process before being finalized.

Design decisions
----------------
Why "DocumentRecord" and collection name "documents" (not "Document"):
    "Document" conflicts with Beanie's base Document class. "DocumentRecord"
    is the Python class name; the MongoDB collection is still called
    "documents" for clean database naming.

Why version tracking:
    Users may request multiple iterations of a cover letter or resume.
    Each iteration is a new DocumentRecord with an incremented version.
    This preserves the history of AI-generated content and lets users
    compare versions or revert to an earlier draft.

Why is_approved flag:
    Human-in-the-loop pattern. Generated documents are drafts until the
    user explicitly approves them. This prevents agents from producing
    content that the user has not reviewed.

    The approval gate is enforced in the LangGraph workflow via
    interrupt() — the workflow pauses until the user approves or
    requests changes.
"""

from beanie import Indexed, PydanticObjectId
from pymongo import ASCENDING, IndexModel

from src.db.base_document import TimestampedDocument
from src.db.documents.enums import DocumentType


class DocumentRecord(TimestampedDocument):
    """
    AI-generated document (cover letter, tailored resume, etc.).

    Fields:
        user_id: Owner of this document.
        application_id: The application this document was generated for.
        doc_type: Type of document (cover_letter, tailored_resume, etc.).
        content: The full generated text content.
        version: Version number within this application + doc_type pair.
        is_approved: Whether the user has approved this version.
        feedback: User's feedback or change requests for the next iteration.
    """

    user_id: PydanticObjectId
    application_id: Indexed(PydanticObjectId)
    doc_type: DocumentType
    content: str = ""
    version: int = 1
    is_approved: bool = False
    feedback: str = ""
    thread_id: str = ""          # LangGraph checkpoint ID for HITL resume
    resume_id: PydanticObjectId | None = None  # Resume used to generate this document

    class Settings:
        name = "documents"
        indexes = [
            IndexModel(
                [("user_id", ASCENDING), ("doc_type", ASCENDING)],
                name="user_doctype_idx",
            ),
            IndexModel(
                [("application_id", ASCENDING), ("doc_type", ASCENDING)],
                name="application_doctype_idx",
            ),
            IndexModel(
                [
                    ("application_id", ASCENDING),
                    ("doc_type", ASCENDING),
                    ("version", ASCENDING),
                ],
                name="application_doctype_version_uidx",
                unique=True,
            ),
        ]
