"""
Nudge document — smart reminders for application status updates and ghost detection.

Each nudge is a single reminder generated by the NudgeEngine when an application
meets timing criteria (stale applied, post-interview outcome check, ghost detection).
The unique compound index on (user_id, application_id, nudge_type) prevents
duplicate nudges for the same application and type.
"""

from datetime import datetime

from beanie import PydanticObjectId
from pydantic import Field
from pymongo import ASCENDING, DESCENDING, IndexModel

from src.db.base_document import TimestampedDocument


class NudgeType:
    """Types of nudges the system can generate."""

    FOLLOW_UP_REMINDER = "follow_up_reminder"
    OUTCOME_CHECK = "outcome_check"
    GHOST_WARNING = "ghost_warning"
    SECOND_FOLLOW_UP = "second_follow_up"
    INTERVIEW_PREP = "interview_prep"


class NudgeStatus:
    """Lifecycle states for a nudge."""

    PENDING = "pending"
    SEEN = "seen"
    DISMISSED = "dismissed"
    ACTED_ON = "acted_on"


class Nudge(TimestampedDocument):
    """
    A smart reminder for the user to update their application tracking.

    Fields:
        user_id: The user this nudge belongs to.
        application_id: The application this nudge is about.
        nudge_type: Type of nudge (follow_up_reminder, outcome_check, etc.).
        status: Lifecycle state (pending, seen, dismissed, acted_on).
        title: Short title for display.
        message: Detailed message with context.
        suggested_actions: List of suggested next steps.
        trigger_date: When the nudge condition was met.
        seen_at: When the user first saw the nudge.
        dismissed_at: When the user dismissed the nudge.
    """

    user_id: PydanticObjectId
    application_id: PydanticObjectId
    nudge_type: str
    status: str = Field(default=NudgeStatus.PENDING)
    title: str = ""
    message: str = ""
    suggested_actions: list[str] = Field(default_factory=list)
    trigger_date: datetime | None = None
    seen_at: datetime | None = None
    dismissed_at: datetime | None = None

    class Settings:
        name = "nudges"
        indexes = [
            IndexModel(
                [("user_id", ASCENDING), ("status", ASCENDING)],
            ),
            IndexModel(
                [
                    ("user_id", ASCENDING),
                    ("application_id", ASCENDING),
                    ("nudge_type", ASCENDING),
                ],
                unique=True,
            ),
            IndexModel(
                [("created_at", DESCENDING)],
            ),
        ]
