"""
Outreach message document model — messages crafted for networking contacts.

Outreach messages are generated by the OutreachComposer agent during the
Application workflow (Stage 3). Each message is tailored to the contact's
role (recruiter, engineer, manager) and goes through approval before being
marked as ready to send.

Design decisions
----------------
Why separate from DocumentRecord:
    Outreach messages have a different lifecycle and different fields than
    cover letters/resumes. They reference a specific Contact (not just an
    Application), track send status, and use a MessageType enum for
    role-based personalization.

    Merging them into DocumentRecord would require nullable fields and
    type-checking everywhere. Separate collections keep each model focused.

Why message_type guides content strategy:
    The OutreachComposer agent generates different messages based on who
    the recipient is:
    - Recruiter: formal, qualification-focused
    - Engineer: technical, project-focused
    - Manager: strategic, impact-focused
    - Generic: balanced approach for unknown roles

    This is configured in the agent's prompt, but storing the type in the
    document enables filtering and analytics (e.g., "which message type
    gets the most responses?").
"""

from datetime import datetime

from beanie import Indexed, PydanticObjectId

from src.db.base_document import TimestampedDocument
from src.db.documents.enums import MessageType


class OutreachMessage(TimestampedDocument):
    """
    Networking outreach message for a specific contact.

    Fields:
        user_id: The sender.
        application_id: The application this outreach supports.
        contact_id: The target contact at the company.
        message_type: Variant based on the contact's role.
        content: The full message text generated by OutreachComposer.
        is_sent: Whether the message has been sent by the user.
        sent_at: When the message was sent. None if not yet sent.
    """

    user_id: PydanticObjectId
    application_id: Indexed(PydanticObjectId)
    contact_id: PydanticObjectId
    message_type: MessageType = MessageType.GENERIC
    content: str = ""
    is_sent: bool = False
    sent_at: datetime | None = None

    class Settings:
        name = "outreach_messages"
